version: 2
jobs:
 build:
   machine:
      image: ubuntu-2004
   steps:
     - checkout
     # start proprietary DB using private Docker image with credentials stored
     # in the UI
     - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     # build the application image
     - run: docker build -t sr258/wp-h5p-shared-state:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker push sr258/wp-h5p-shared-state:$CIRCLE_BRANCH
